version: '3'
services:
  jupyter:
    image: jupyter/datascience-notebook:latest
    container_name: DSTI_Python_Lab_A22
    ports:
      - 8888:8888
    environment:
      JUPYTER_ENABLE_LAB: "yes"
      JUPYTER_TOKEN: "docker"
